[env:esp32-s3]
platform = espressif32@7.0.1
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

lib_deps =
    https://github.com/meshtastic/codec2.git#3e347e0b70fc72af9357fbbd32b10a125321d6c5

build_flags =
    -DCODEC2_MODE_EN_DEFAULT=0
    -DCODEC2_MODE_2400_EN=1
